name: e2e plus tests
on: 
#  push:
#    branches:
#      - main
#    paths-ignore:
#      - '**.md'
#  pull_request:
#    paths-ignore:
#      - '**.md'
  workflow_dispatch:

jobs:

  e2e-plus-tests:

    timeout-minutes: 15

    runs-on: ubuntu-latest

    steps:

      - name: install redis service
        uses: pfapi/redis-cluster-service@v1

      - name: Checkout pfapi/pfapi
        uses: actions/checkout@v3

      - name: Install dependencies for pfapi-dev-test
        run: cd main; yarn install

      - name: copy redis-env
        run: cd main; cp tools/redis-env .env

      - name: start mysql service
        run: sudo systemctl restart mysql

      - name: set to use mysql database config
        run: cd main; cp tools/db-mysql.js config/database.js

      - name: set mylogin.cnf
        run: cd main; cp tools/mylogin.cnf ~/.mylogin.cnf ; chmod 600 ~/.mylogin.cnf

      - name: run sql show databases
        run: mysql --login-path=local -e "show databases"

      - name: run prepare
        run: cd main; node tools/prepare

      - name: Build strapi
        run: cd main; yarn build

      - name: start redis cluster service
        run: sudo systemctl start redis-cluster

      - name: set nginx config
        run: cd main; sudo cp tools/nginx.conf /etc/nginx/nginx.conf

      - name: start nginx service
        run: sudo systemctl restart nginx

      - name: Run strapi on port 8181
        run: cd main; PORT=8181 yarn develop &

      - name: Wait Util Ready on port 8181
        run: cd main; node tools/wait-util-ready.js 8181

      - name: Run strapi on port 8282
        run: cd main; PORT=8282 yarn develop &

      - name: Wait Util Ready on port 8282
        run: cd main; node tools/wait-util-ready.js 8282

      - name: Wait Util Ready nginx
        run: cd main; node tools/wait-util-ready.js

      - name: run yarn test
        run: cd main; yarn test

      - name: Install @pfapi/tester
        run: npm install @pfapi/tester --location=global

      - name: run pfapi-tester 1 time with verbose 
        run: pfapi-tester -t 1 -v

      - name: run pfapi-tester 10 times and concurrent
        run: pfapi-tester -t 10 -c

      - name: run pfapi-tester fetch items and concurrent
        run: pfapi-tester -f -c

      - name: run pfapi-tester walk through and fetch items
        run: pfapi-tester -w -f
