name: tests
on: 
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:
  
jobs:

  tests:

    timeout-minutes: 15

    runs-on: ubuntu-latest

    steps:

      - name: add redis repo
        run: curl -fsSL https://packages.redis.io/gpg | sudo gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg ; echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/redis.list

      - name: update
        run: sudo apt-get update -y

      - name: install redis
        run: sudo apt-get install redis -y
        
      - name: remove protected-mode
        run: sudo sed -i 's/protected-mode yes/protected-mode no/' /etc/redis/redis.conf

      - name: start redis
        run: sudo systemctl restart redis-server

      - name: Checkout pfapi/pfapi-core
        uses: actions/checkout@v3
        with:
            repository: pfapi/pfapi-core
            path: pfapi-core

      - name: run npm install
        run: cd pfapi-core; npm install
  
      - name: run npm test
        run: cd pfapi-core; npm test