name: integrated tests
on: 
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:

  integrated-tests:

    timeout-minutes: 15

    runs-on: ubuntu-latest

    steps:

      - name: install redis service
        uses: pfapi/redis-cluster-service@v1

      - name: start redis service
        run: sudo systemctl restart redis-server

      - name: start mysql service
        run: sudo systemctl restart mysql

      - name: Checkout pfapi/pfapi-dev-test
        uses: actions/checkout@v3
        with:
            repository: pfapi/pfapi-dev-test
            path: main

      - name: Install dependencies for pfapi-dev-test
        run: cd main; yarn install

      - name: Checkout pfapi/pfapi
        uses: actions/checkout@v3
        with:
            repository: pfapi/pfapi
            path: main/src/plugins/pfapi

      - name: Install dependencies for pfapi
        run: cd main/src/plugins/pfapi; yarn install

      - name: set to sqlite database config
        run: cd main; cp tools/db-sqlite.js config/database.js

      - name: run prepare
        run: cd main; node tools/prepare

      - name: run tree
        run: tree -I 'node_modules|cache|build'

      - name: Build & Run strapi
        run: cd main; yarn build; yarn develop &

      - name: Wait Util Ready
        run: cd main; node tools/wait-util-ready.js

      - name: run yarn test
        run: cd main; yarn test

      - name: Install @pfapi/tester
        run: npm install @pfapi/tester --location=global
        
      - name: run pfapi-tester 1 time with verbose 
        run: pfapi-tester -t 1 -v

      - name: run pfapi-tester 10 times and concurrent
        run: pfapi-tester -t 10 -c

      - name: run pfapi-tester fetch items and concurrent
        run: pfapi-tester -t 1 -f -c

      - name: run pfapi-tester walk through and fetch items
        run: pfapi-tester -w -f