name: publish
on:
  pull_request:
    types: [closed]
    branches:
      - development
      - main
  workflow_dispatch:

jobs:
  publish:
    if: github.event.pull_request.merged == true
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: setup git config
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

    - name: setup npm credential
      run: npm set "//registry.npmjs.org/:_authToken=$NPM_TOKEN"
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: version and publish
      run: |
        if [ "${GITHUB_REF##*/}" = main ]; then
          npx lerna version --conventional-commits --conventional-graduate --yes
        else
          npx lerna version --conventional-commits --conventional-prerelease --preid beta --yes
        fi
        npx lerna publish from-git --yes
      env:
        GH_TOKEN: ${{ secrets.ACCESS_PASS }}

    - name: release 
      uses: pfapi/pfapi/.github/workflows/release.yaml
