name: publish
on:
  # pull_request:
  #   types: [closed]
  #   branches:
  #     - development
  #     - main
  workflow_dispatch:

jobs:
  publish:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: git branch
      run: git branch ; echo "GITHUB_REF=$GITHUB_REF" ; echo "branch=${GITHUB_REF##*/}"

    - name: setup npm credential
      run: |
        npm set @pfapi:registry=https://npm.pkg.github.com/pfapi
        npm set "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}"

    - name: setup git config and credentials
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor}}@users.noreply.github.com"
        echo "https://${{ secrets.ACCESS_TOKEN }}@github.com" > ~/.git-credentials
        chmod 600 ~/.git-credentials

    - name: cleanup credential files
      run: |
        [ -f ~/.npmrc ] && rm ~/.npmrc
        [ -f ~/.git-credentials ] && rm ~/.git-credentials
        [ -f ~/.gitconfig ] && rm ~/.gitconfig