name: release

on: 
  pull_request:
    branches:
      - main
    types: 
      - opened
      - reopened
      - synchronize
      - edited
  workflow_dispatch:

jobs:

  release:
     
    timeout-minutes: 15

    runs-on: ubuntu-latest

    steps:

      - name: only allow pull request from development
        if: github.head_ref != 'development'
        run: |
          echo "pull request from ${{ github.head_ref }} is not allowed"
          exit 1

      - name: install redis service
        uses: pfapi/redis-cluster-service@v1
  
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Checkout all branches and tags

      - name: setup
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config advice.detached head false
          npm set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"
          echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV
          echo "ISSUE_URL=${{ github.api_url }}/repos/${{ github.repository }}/issues/${{ github.event.number }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install && npx lerna bootstrap

      - name: use mysql and redis cluster
        run: npx lerna run use-my-plus --stream

      - name: Build
        run: npx lerna run build --stream

      - name: Run strapi on port 8181
        run: PORT=8181 npx lerna run develop --stream &

      - name: Wait Util Ready on port 8181
        run: PORT=8181 npx lerna run wait-ready --stream 

      - name: Run strapi on port 8282
        run: PORT=8282 npx lerna run develop --stream &

      - name: Wait Util Ready on port 8282
        run: PORT=8282 npx lerna run wait-ready --stream 

      - name: start nginx
        run: sudo systemctl restart nginx

      - name: Wait Util Ready nginx
        run: npx lerna run wait-ready --stream 

      - name: Run test
        run: npx lerna run test --stream

      - name: restart nginx
        run: sudo systemctl restart nginx

      - name: Wait Util Ready
        run: npx lerna run wait-ready --stream

      - name: run pfapi-tester 1 time with verbose 
        run: npx pfapi-tester -t 1 -v

      - name: run pfapi-tester 10 times and concurrent
        run: npx pfapi-tester -t 10 -c

      - name: run pfapi-tester 1 time, fetch items and concurrent
        run: npx pfapi-tester -t 1 -f -c

      - name: run pfapi-tester walk through and fetch items
        run: npx pfapi-tester -w -f

      - name: commit and merge into GITHUB_BASE_REF
        run: |
          git restore packages/strapi-app/.env
          git add .
          git commit -m "commit $GITHUB_REF_NAME by $GITHUB_JOB" || true
          git branch temporary-work
          git checkout $GITHUB_BASE_REF 
          git merge temporary-work -m "merge $GITHUB_REF_NAME by $GITHUB_JOB" || true

      - name: get BUMP from pull request title
        run: bin/get-pr-bump

      - name: version & publish
        run: |
          npx lerna version $BUMP --exact --no-private --conventional-commits --conventional-graduate --create-release=github --yes
          npx lerna publish from-git --yes --dist-tag latest

      - name: update lerna.json version to development
        run: |
          cp lerna.json /tmp
          git checkout development
          git pull
          cp /tmp/lerna.json .
          git add lerna.json
          git commit -m "update lerna.json version by $GITHUB_JOB" || true
          git push || true