name: tests

on:
  pull_request:
    branches:
      - development
  workflow_dispatch:


jobs:

  tests:

    timeout-minutes: 15

    runs-on: ubuntu-latest

    steps:

      - name: install redis service
        uses: pfapi/redis-cluster-service@v1

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Checkout all branches and tags

      - name: setup
        run: |
          git config --global user.name "$GITHUB_REPOSITORY_OWNER"
          git config --global user.email "$GITHUB_REPOSITORY_OWNER@users.noreply.github.com"
          git config --global advice.detachedHead false
          npm set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"
          echo "API_URL=${{ github.api_url }}/repos/${{ github.repository }}" >> $GITHUB_ENV
          echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install && npx lerna bootstrap

      - name: Build
        run: npx lerna run build --stream

      - name: Run test
        run: npx lerna run test --stream

      - name: Start strapi develop
        run: npx lerna run develop --stream &

      - name: Wait Util Ready
        run: npx lerna run wait-ready --stream

      - name: run pfapi-tester 1 time with verbose 
        run: npx pfapi-tester -t 1 -v

      - name: run pfapi-tester 10 times and concurrent
        run: npx pfapi-tester -t 10 -c

      - name: run pfapi-tester 1 time, fetch items and concurrent
        run: npx pfapi-tester -t 1 -f -c

      - name: run pfapi-tester walk through and fetch items
        run: npx pfapi-tester -w -f

      - name: pull request merge
        if: env.GH_TOKEN != ''
        run: .github/bin/pr-merge-simple

      - name: version & publish
        if: env.GH_TOKEN != ''
        run: |
          npx lerna version --exact --no-private --conventional-commits --conventional-prerelease --preid beta --yes
          npx lerna publish from-git --yes --dist-tag beta

      - name: finish the commit
        if: env.GH_TOKEN != ''
        run: .github/bin/finish-commit