name: verify npm release

on:
  workflow_dispatch:
  release:
    types: 
      - created

jobs:

  verify-npm-release:

    timeout-minutes: 15

    runs-on: ubuntu-latest

    steps:
      
      - name: install redis service
        uses: pfapi/redis-cluster-service@v1

      - name: Checkout pfapi/pfapi
        uses: actions/checkout@v3

      - name: install strapi-app dependencies
        run: cd packages/strapi-app; npm install

      - name: build strapi-app
        run: cd packages/strapi-app; npm run build

      - name: run develop
        run: cd packages/strapi-app; npm run develop &

      - name: Wait Util Ready
        run: cd packages/strapi-app; npm run wait-ready

      - name: run test
        run: cd packages/strapi-app; npm run test

      - name: Install @pfapi/tester
        run: npm install @pfapi/tester -g
        
      - name: run pfapi-tester 1 time with verbose 
        run: pfapi-tester -t 1 -v

      - name: run pfapi-tester 10 times and concurrent
        run: pfapi-tester -t 10 -c

      - name: run pfapi-tester 1 time, fetch items and concurrent
        run: npx pfapi-tester -t 1 -f -c

      - name: run pfapi-tester walk through and fetch items
        run: pfapi-tester -w -f
